// AUTO-GENERATED — do not edit manually.
// Source: packages/data/src/reason-codes.js
// Regenerate: node scripts/generate-reason-labels.js
// Inlined here to avoid pulling the server-only @cheddar-logic/data package
// (which depends on better-sqlite3) into the client bundle.

export const REASON_CODE_LABELS: Record<string, string> = Object.freeze({
  PASS_NO_EDGE: 'No edge',
  NO_EDGE_AT_PRICE: 'Price too sharp',
  PASS_DRIVER_SUPPORT_WEAK: 'Driver support weak',
  PASS_CONFLICT_HIGH: 'Conflicting signals',
  SUPPORT_BELOW_LEAN_THRESHOLD: 'Insufficient support',
  SUPPORT_BELOW_PLAY_THRESHOLD: 'Insufficient support',
  NO_PRIMARY_SUPPORT: 'Insufficient model support',
  PASS_LOW_CONFIDENCE: 'Low confidence',
  PASS_SHARP_MONEY_OPPOSITE: 'Sharp money against',
  SIGMA_FALLBACK_DEGRADED: 'Sigma fallback \u2014 degraded confidence',
  PLAY_CONTRADICTION_CAPPED: 'Contradicting signals \u2014 capped to lean',
  NHL_1P_OVER_LEAN: 'Lean only \u2014 1P over',
  NHL_1P_UNDER_LEAN: 'Lean only \u2014 1P under',
  NHL_ML_LEAN: 'Lean only \u2014 ML',
  NHL_1P_OVER_PLAY: 'Play \u2014 1P over',
  NHL_1P_UNDER_PLAY: 'Play \u2014 1P under',
  NHL_ML_PLAY: 'Play \u2014 ML',
  FIRST_PERIOD_PROJECTION_LEAN: 'Lean \u2014 1P projection',
  FIRST_PERIOD_PROJECTION_PLAY: 'Play \u2014 1P projection',
  MISSING_DATA_PROJECTION_INPUTS: 'Missing projection inputs',
  MISSING_DATA_FEATURE_FRESHNESS: 'Feature freshness stale',
  MISSING_DATA_DRIVERS: 'Driver output unavailable',
  MISSING_DATA_TEAM_MAPPING: 'Team mapping unresolved',
  MISSING_DATA_NO_ODDS: 'Odds unavailable',
  PASS_MISSING_DRIVER_INPUTS: 'Missing driver inputs',
  PASS_DATA_ERROR: 'Data error \u2014 no play',
  WATCHDOG_CONSISTENCY_MISSING: 'Projection inputs missing',
  WATCHDOG_PARSE_FAILURE: 'Model data unavailable',
  MODEL_PROB_MISSING: 'Model incomplete',
  MARKET_PRICE_MISSING: 'Market price unavailable',
  MARKET_EDGE_UNAVAILABLE: 'Edge unavailable at current market',
  PARSE_FAILURE: 'Model data unavailable',
  STALE_SNAPSHOT: 'Snapshot stale',
  ESPN_NULL_OBSERVATION: 'ESPN feed null',
  ESPN_NULL_ALERT_FAILED: 'ESPN null alert failed',
  TIMESTAMP_MISSING: 'Timestamp missing',
  TIMESTAMP_PARSE_ERROR: 'Timestamp invalid',
  TIMESTAMP_AGE_INVALID: 'Timestamp too old',
  GAME_ID_INVALID: 'Game ID invalid',
  AVAILABILITY_GATE_DEGRADED: 'Availability gate degraded',
  LINE_DELTA_COMPUTATION_FAILED: 'Line delta unavailable',
  LINE_CONTEXT_MISSING: 'Line context missing',
  CAPTURED_AT_MISSING: 'Capture time missing',
  CAPTURED_AT_MS_INVALID: 'Capture time invalid',
  NEUTRAL_VALUE_COERCE_SILENT: 'Neutral value coerced',
  PRICE_VALIDATION_FAILED: 'Price validation failed',
  STALE_RECOVERY_REFRESH_FAILED: 'Stale recovery failed',
  STALE_RECOVERY_RELOAD_FAILED: 'Stale reload failed',
  LINE_NOT_CONFIRMED: 'Line not confirmed',
  EDGE_RECHECK_PENDING: 'Edge needs recheck before action',
  EDGE_NO_LONGER_CONFIRMED: 'Edge no longer clears threshold',
  STALE_MARKET: 'Market data stale',
  PRICE_SYNC_PENDING: 'Book price still syncing',
  BLOCKED_BET_VERIFICATION_REQUIRED: 'Waiting on line verification',
  GATE_LINE_MOVEMENT: 'Line moved \u2014 re-evaluating',
  WATCHDOG_MARKET_UNAVAILABLE: 'Market unavailable',
  EDGE_SANITY_NON_TOTAL: 'Edge sanity check failed',
  LINE_MOVE_ADVERSE: 'Line moved adversely',
  PRICE_STALE: 'Price stale versus signal',
  PLAY_REQUIRES_FRESH_MARKET: 'Play requires fresh market data',
  STARTER_UNCONFIRMED: 'Starter not confirmed',
  STARTER_MISMATCH: 'Starter mismatch versus priced assumption',
  BEST_LINE_UNCONFIRMED: 'Best line not confirmed',
  WEATHER_STATUS_PENDING: 'Weather status pending',
  MARKET_SOURCE_UNCONFIRMED: 'Market source unconfirmed',
  HEAVY_FAVORITE_PRICE_CAP: 'High price cap',
  FIRST_PERIOD_NO_PROJECTION: 'No 1P projection available',
  EXACT_WAGER_MISMATCH: 'Line mismatch',
  PROXY_EDGE_BLOCKED: 'Edge blocked by proxy cap',
  PROXY_EDGE_CAPPED: 'Edge capped by proxy',
  GATE_GOALIE_UNCONFIRMED: 'Waiting on goalie confirmation',
  BLOCK_INJURY_RISK: 'Injury risk flag',
  GOALIE_UNCONFIRMED: 'Waiting on goalie confirmation',
  GOALIE_CONFLICTING: 'Conflicting goalie reports',
  INJURY_UNCERTAIN: 'Injury status uncertain',
  PASS_EXECUTION_GATE_CONFIDENCE_BELOW_THRESHOLD: 'Model edge present, blocked by confidence gate',
  PASS_EXECUTION_GATE_NET_EDGE_INSUFFICIENT: 'No edge at current price',
  PASS_EXECUTION_GATE_NO_EDGE_COMPUTED: 'Model incomplete',
  PASS_EXECUTION_GATE_BLOCKED: 'Blocked by execution gate',
  PASS_EXECUTION_GATE_LOW_EDGE: 'Edge below execution threshold',
  PASS_EXECUTION_GATE_NO_EDGE: 'No edge at execution',
  PASS_EXECUTION_GATE_STALE_SNAPSHOT: 'Stale snapshot at execution',
  PASS_EXECUTION_GATE_MIXED_BOOK_SOURCE_MISMATCH: 'Book source mismatch',
  EDGE_CLEAR: 'Edge clear',
  EDGE_FOUND_SIDE: 'Edge found',
  EDGE_FOUND: 'Edge found',
});

export function getReasonCodeLabel(code?: string | null): string | null {
  if (!code) return null;
  const token = String(code)
    .trim()
    .toUpperCase()
    .replace(/[\s-]+/g, '_');
  if (!token) return null;
  if (REASON_CODE_LABELS[token]) return REASON_CODE_LABELS[token];
  if (token.includes('GOALIE')) return 'Waiting on goalie confirmation';
  return null;
}
