// AUTO-GENERATED — do not edit manually.
// Source: packages/data/src/reason-codes.js
// Regenerate: node scripts/generate-reason-labels.js
// Inlined here to avoid pulling the server-only @cheddar-logic/data package
// (which depends on better-sqlite3) into the client bundle.

export const REASON_CODE_LABELS: Record<string, string> = Object.freeze({
  PASS_NO_EDGE: 'No edge',
  PASS_MISSING_EDGE: 'Edge unavailable',
  PASS_DIRECTION_MISMATCH: 'Direction mismatches market side',
  BASE_PLAY_DELTA_GTE_1_0: 'Base play threshold met',
  BASE_SLIGHT_EDGE_DELTA_GTE_0_5: 'Base slight-edge threshold met',
  BASE_PASS_DELTA_LT_0_5: 'Base delta below slight-edge threshold',
  FRAGILITY_UNDER_5_5: 'Under 5.5 fragility cap applied',
  FRAGILITY_OVER_6_5_ACCELERANT_BELOW_0_20: 'Over 6.5 lacks scoring accelerant',
  OVER_6_5_ACCELERANT_OK: 'Over 6.5 scoring accelerant confirmed',
  FLOOR_GUARD_FORCE_PASS_DELTA_LT_0_5: 'Floor guard forced pass below threshold',
  ANTI_FLATTENING_RESTORE_PLAY: 'Play restored after anti-flattening check',
  NO_EDGE_AT_PRICE: 'Price too sharp',
  PASS_DRIVER_SUPPORT_WEAK: 'Driver support weak',
  PASS_CONFLICT_HIGH: 'Conflicting signals',
  SUPPORT_BELOW_LEAN_THRESHOLD: 'Insufficient support',
  SUPPORT_BELOW_PLAY_THRESHOLD: 'Insufficient support',
  NO_PRIMARY_SUPPORT: 'Insufficient model support',
  PASS_LOW_CONFIDENCE: 'Low confidence',
  PASS_SHARP_MONEY_OPPOSITE: 'Sharp money against',
  SIGMA_FALLBACK_DEGRADED: 'Sigma fallback \u2014 degraded confidence',
  PLAY_CONTRADICTION_CAPPED: 'Contradicting signals \u2014 capped to lean',
  NHL_1P_OVER_LEAN: 'Lean only \u2014 1P over',
  NHL_1P_UNDER_LEAN: 'Lean only \u2014 1P under',
  NHL_ML_LEAN: 'Lean only \u2014 ML',
  NHL_1P_OVER_PLAY: 'Play \u2014 1P over',
  NHL_1P_UNDER_PLAY: 'Play \u2014 1P under',
  NHL_ML_PLAY: 'Play \u2014 ML',
  FIRST_PERIOD_PROJECTION_LEAN: 'Lean \u2014 1P projection',
  FIRST_PERIOD_PROJECTION_PLAY: 'Play \u2014 1P projection',
  MISSING_DATA_PROJECTION_INPUTS: 'Missing projection inputs',
  MISSING_DATA_DRIVERS: 'Driver output unavailable',
  MISSING_DATA_TEAM_MAPPING: 'Team mapping unresolved',
  MISSING_DATA_NO_ODDS: 'Odds unavailable',
  MISSING_DATA_FEATURE_FRESHNESS: 'Feature freshness stale',
  MISSING_DATA_MARKET_TYPES: 'Market missing required types',
  PASS_MISSING_DRIVER_INPUTS: 'Missing driver inputs',
  PASS_MISSING_SELECTION: 'Selection unavailable',
  PASS_MISSING_LINE: 'Line unavailable',
  PASS_MISSING_PRICE: 'Price unavailable',
  PASS_NO_MARKET_PRICE: 'Market price unavailable',
  PASS_MISSING_REQUIRED_INPUTS: 'Missing required inputs',
  PASS_INTEGRITY_BLOCK: 'Integrity block',
  PASS_DATA_ERROR: 'Data error \u2014 no play',
  WATCHDOG_CONSISTENCY_MISSING: 'Projection inputs missing',
  WATCHDOG_PARSE_FAILURE: 'Model data unavailable',
  MODEL_PROB_MISSING: 'Model incomplete',
  MARKET_PRICE_MISSING: 'Market price unavailable',
  MARKET_EDGE_UNAVAILABLE: 'Edge unavailable at current market',
  PARSE_FAILURE: 'Model data unavailable',
  STALE_SNAPSHOT: 'Snapshot stale',
  ESPN_NULL_OBSERVATION: 'ESPN feed null',
  ESPN_NULL_ALERT_FAILED: 'ESPN null alert failed',
  TIMESTAMP_MISSING: 'Timestamp missing',
  TIMESTAMP_PARSE_ERROR: 'Timestamp invalid',
  TIMESTAMP_AGE_INVALID: 'Timestamp too old',
  GAME_ID_INVALID: 'Game ID invalid',
  AVAILABILITY_GATE_DEGRADED: 'Availability gate degraded',
  LINE_DELTA_COMPUTATION_FAILED: 'Line delta unavailable',
  LINE_CONTEXT_MISSING: 'Line context missing',
  CAPTURED_AT_MISSING: 'Capture time missing',
  CAPTURED_AT_MS_INVALID: 'Capture time invalid',
  NEUTRAL_VALUE_COERCE_SILENT: 'Neutral value coerced',
  PRICE_VALIDATION_FAILED: 'Price validation failed',
  STALE_RECOVERY_REFRESH_FAILED: 'Stale recovery failed',
  STALE_RECOVERY_RELOAD_FAILED: 'Stale reload failed',
  LINE_NOT_CONFIRMED: 'Line not confirmed',
  EDGE_RECHECK_PENDING: 'Edge needs recheck before action',
  EDGE_NO_LONGER_CONFIRMED: 'Edge no longer clears threshold',
  STALE_MARKET: 'Market data stale',
  PRICE_SYNC_PENDING: 'Book price still syncing',
  BLOCKED_BET_VERIFICATION_REQUIRED: 'Waiting on line verification',
  GATE_LINE_MOVEMENT: 'Line moved \u2014 re-evaluating',
  WATCHDOG_MARKET_UNAVAILABLE: 'Market unavailable',
  EDGE_SANITY_NON_TOTAL: 'Edge sanity check failed',
  LINE_MOVE_ADVERSE: 'Line moved adversely',
  PRICE_STALE: 'Price stale versus signal',
  PLAY_REQUIRES_FRESH_MARKET: 'Play requires fresh market data',
  STARTER_UNCONFIRMED: 'Starter not confirmed',
  STARTER_MISMATCH: 'Starter mismatch versus priced assumption',
  BEST_LINE_UNCONFIRMED: 'Best line not confirmed',
  WEATHER_STATUS_PENDING: 'Weather status pending',
  MARKET_SOURCE_UNCONFIRMED: 'Market source unconfirmed',
  HEAVY_FAVORITE_PRICE_CAP: 'High price cap',
  FIRST_PERIOD_NO_PROJECTION: 'No 1P projection available',
  EXACT_WAGER_MISMATCH: 'Line mismatch',
  PROXY_EDGE_BLOCKED: 'Edge blocked by proxy cap',
  PROXY_EDGE_CAPPED: 'Edge capped by proxy',
  GATE_GOALIE_UNCONFIRMED: 'Waiting on goalie confirmation',
  BLOCK_INJURY_RISK: 'Injury risk flag',
  GOALIE_UNCONFIRMED: 'Waiting on goalie confirmation',
  GOALIE_CONFLICTING: 'Conflicting goalie reports',
  INJURY_UNCERTAIN: 'Injury status uncertain',
  CAP_GOALIES_UNCONFIRMED: 'Goalies unconfirmed \u2014 cap applied',
  CAP_MAJOR_INJURY_UNCERTAINTY: 'Major injury uncertainty \u2014 cap applied',
  DOWNGRADE_PLAY_TO_SLIGHT_EDGE_GOALIE_UNCERTAINTY: 'Goalie uncertainty downgraded play to slight edge',
  DOWNGRADE_PLAY_TO_SLIGHT_EDGE_INJURY_UNCERTAINTY: 'Injury uncertainty downgraded play to slight edge',
  DOWNGRADE_SLIGHT_EDGE_TO_PASS_INJURY_UNCERTAINTY_THIN_EDGE: 'Thin edge downgraded to pass by injury uncertainty',
  DOWNGRADE_PLAY_TO_SLIGHT_EDGE_UNDER_5_5: 'Under 5.5 fragility downgraded play to slight edge',
  DOWNGRADE_SLIGHT_EDGE_TO_PASS_UNDER_5_5: 'Under 5.5 fragility downgraded slight edge to pass',
  DOWNGRADE_PLAY_TO_SLIGHT_EDGE_OVER_6_5: 'Over 6.5 fragility downgraded play to slight edge',
  DOWNGRADE_SLIGHT_EDGE_TO_PASS_OVER_6_5: 'Over 6.5 fragility downgraded slight edge to pass',
  PASS_EXECUTION_GATE_CONFIDENCE_BELOW_THRESHOLD: 'Model edge present, blocked by confidence gate',
  PASS_EXECUTION_GATE_NET_EDGE_INSUFFICIENT: 'No edge at current price',
  PASS_EXECUTION_GATE_NO_EDGE_COMPUTED: 'Model incomplete',
  PASS_EXECUTION_GATE_BLOCKED: 'Blocked by execution gate',
  PASS_EXECUTION_GATE_LOW_EDGE: 'Edge below execution threshold',
  PASS_EXECUTION_GATE_NO_EDGE: 'No edge at execution',
  PASS_EXECUTION_GATE_STALE_SNAPSHOT: 'Stale snapshot at execution',
  PASS_EXECUTION_GATE_MIXED_BOOK_SOURCE_MISMATCH: 'Book source mismatch',
  PASS_CONFIDENCE_GATE: 'Edge present \u2014 blocked by confidence gate',
  PROJECTION_ONLY_EXCLUSION: 'Excluded \u2014 projection-only path',
  PASS_NO_DISTRIBUTION: 'No probability distribution computed',
  PASS_UNKNOWN: 'Pass \u2014 reason unknown',
  SOFT_WEAK_DRIVER_SUPPORT: 'Soft advisory \u2014 weak driver support',
  MARKET_SANITY_FAIL: 'Market sanity check failed',
  MODEL_DEGRADED_INPUTS: 'Model received degraded inputs',
  PASS_DEGRADED_TOTAL_MODEL: 'Pass \u2014 total model degraded',
  PASS_INPUTS_INCOMPLETE: 'Pass \u2014 required inputs incomplete',
  PASS_MODEL_DEGRADED: 'Pass \u2014 model degraded',
  PASS_PROJECTION_ONLY_NO_MARKET: 'Pass \u2014 projection only, no market line',
  PASS_SYNTHETIC_FALLBACK: 'Pass \u2014 synthetic fallback data used',
  SOFT_DEGRADED_TOTAL_MODEL: 'Soft advisory \u2014 total model degraded',
  SOFT_MARKET_SANITY_FAIL: 'Soft advisory \u2014 market sanity check failed',
  PASS_FEATURE_TIMESTAMP_LEAK: 'Pass \u2014 feature data leaked future timestamp',
  EDGE_CLEAR: 'Edge clear',
  EDGE_FOUND_SIDE: 'Edge found',
  EDGE_FOUND: 'Edge found',
});

export function getReasonCodeLabel(code?: string | null): string | null {
  if (!code) return null;
  const token = String(code)
    .trim()
    .toUpperCase()
    .replace(/[\s-]+/g, '_');
  if (!token) return null;
  if (REASON_CODE_LABELS[token]) return REASON_CODE_LABELS[token];
  if (token.includes('GOALIE')) return 'Waiting on goalie confirmation';
  return null;
}
